services:
  portsshare:
    container_name: portsshare-tunnels
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # Create a .env file to contain the SSH key name value or reference directly below.
      - SSHKEY=portsshare-id_ed25519
    stdin_open: true # docker run -i
    tty: true # docker run -t
      #
    volumes:
      # Bind the config file so it can be edited without rebuilding the image
      - ~/config.yaml:/config.yaml
      # Bind an SSH key that is authorised to connect to the desired target machines
      - ./keys:/root/.ssh
    restart: unless-stopped
    networks: 
      - portsshare
    ports:
      # set the number of ports required. Keeping the number to a minimum can help container performance and prevent impact to docker apps like Portainer
      - 10001-10015:10001-10015 
   
networks:
  portsshare:
    driver: bridge
    name: portsshare
