services:
  autossh-tunnel:
    container_name: ${CONTAINER_NAME:-portsshare}
    build: .
    volumes:
      # Bind the config file so it can be edited without rebuilding the image
      - ./config.yaml:/config.yaml
      # Bind the host's SSH keys so container appears as an authorized key
      - ~/.ssh:/root/.ssh
    restart: always
